### ISSUE TITLE
Pending issues

### ISSUE THREAD

**Issue by amit10may** [Lavanya-nrg/SQL-PYTHON-ASSIGNMENT#2]
I do not see fixes for requirements.txt versions, secrets externalized into env file.
Is that something you have fixed but not yet pushed?

**Comment by Lavanya-nrg** [comment]
Sir there is no dependency of project on the versions this is why i didn’t mention then and sir I have to create a virtual environment. Kanchan asked me to just just replace the parameters and write a comment in that line but I will now learn about the virtual environment and create it for the repository

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Amit Mujawar ***@***.***>
Sent: Monday, February 26, 2024 3:18:11 PM
To: Lavanya-nrg/SQL-PYTHON-ASSIGNMENT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Lavanya-nrg/SQL-PYTHON-ASSIGNMENT] Pending issues (Issue #2)


I do not see fixes for requirements.txt versions, secrets externalized into env file.
Is that something you have fixed but not yet pushed?

**Comment by amit10may** [comment]
Ok versions thing makes sense. What about externalizing the configurations like username/pwd?

**Comment by Lavanya-nrg** [comment]
I am just about to work on it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amit10may** [comment]
I still see this open - if u have fixed it, please resolve the issue and keep status report updated.

**Comment by Lavanya-nrg** [comment]
issue closed #2
